version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: logpilot-postgres
    restart: always
    environment:
      POSTGRES_USER: logpilot_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: logpilot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ${PWD}/data:/var/lib/clickhouse
      - ${PWD}/logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_USER=logpilot
      - CLICKHOUSE_PASSWORD=logpilot
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=logpilot
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    ports:
      - "8123:8123"
volumes:
  postgres_data:
  clickhouse_data:
